spring:
  elasticsearch:
    rest:
      password: ''
      uris: http://localhost:9200
      username: ''
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-xxx/.well-known/jwks.json
  session:
    store-type: none

springdoc:
  paths-to-exclude:
    - '/profile/**'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health